# SPDX-FileCopyrightText: 2026 VaiTon <eyadlorenzo@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Static Site

on:
  push:
    branches: ["main"] # Or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-slim

    env:
      FOLDERS: "esercizi"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # ratchet:actions/configure-pages@v5

      - name: Build website
        run: ./scripts/build_website ${FOLDERS} --baseurl ${{ steps.setup-pages.outputs.base_url }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # ratchet:actions/upload-pages-artifact@v4
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # ratchet:actions/deploy-pages@v4
